version: v2
budget: ai2/oe-training
description: unshard peteish7b checkpoints
tasks:
  - name: unshard-peteish-remaining-checkpoints
    image:
      beaker: ai2/cuda11.8-ubuntu20.04
    command:
      - /bin/bash
      - -c
      - /myfiles/amanr/unshard_normal.sh
    datasets:
      - mountPath: /myfiles
        source:
          weka: oe-training-default
    context:
      preemptible: true
    constraints:
      cluster:
        - ai2/allennlp-elara-cirrascale