version: v2
budget: ai2/oe-training
description: Unshardand upload peteish13b checkpoints to hf
tasks:
  - name: unshard-upload-peteish13-hf
    image:
      beaker: ai2/cuda11.8-ubuntu20.04
    command:
      - /bin/bash
      - -c
      - /myfiles/amanr/unshard_upload_hf_gs.sh
    datasets:
      - mountPath: /myfiles
        source:
          weka: oe-training-default
    context:
      preemptible: true
    constraints:
      cluster:
        - ai2/allennlp-elara-cirrascale